import wx as wx

class MainWindow(wx.Panel):
    def __init__(self,parent):
        wx.Panel.__init__(self,parent)
        self.table1Title = wx.StaticText(self,label="Instructions' State",pos=(50,140))
        self.table1 = wx.ListCtrl(self,name="instructions'State",style=wx.LC_REPORT,pos=(50,160),size=(700,150))
        self.table1.AppendColumn("IF")
        self.table1.AppendColumn("EX start")
        self.table1.AppendColumn("EX end")
        self.table1.AppendColumn("WB")
        self.table2Title = wx.StaticText(self,label="Register' State",pos=(450,30))
        self.table2 = wx.ListCtrl(self,name="register'State",style=wx.LC_REPORT,pos=(450,50),size=(300,80))
        self.table2.AppendColumn("")
        self.table2.Append(["Qi"])
        self.table3Title = wx.StaticText(self,label="Functional Units",pos=(50,330))
        self.table3 = wx.ListCtrl(self,name="functional Units",style=wx.LC_REPORT,pos=(50,350),size=(700,150))
        self.table3.AppendColumn("UF")
        self.table3.AppendColumn("Busy")
        self.table3.AppendColumn("Op")
        self.table3.AppendColumn("Qj")
        self.table3.AppendColumn("Qk")
        self.table3.AppendColumn("Vj")
        self.table3.AppendColumn("Vk")
        self.table3.AppendColumn("A")
        self.table4Title = wx.StaticText(self,label="Main Memory",pos=(50,30))
        self.table4 = wx.ListCtrl(self,name="main Memory",style=wx.LC_REPORT,pos=(50,50),size=(300,80))
        self.table4.AppendColumn("Memory Address")
        self.table4.Append(["Content"])
        self.button = wx.Button(self,label="Next",pos=(50,530))

app = wx.App(True)
frame = wx.Frame(None,title="Tomasulo's algorithm simulator",size=(800,600))
panel = MainWindow(frame)
frame.Show()
app.MainLoop()
